<a href="https://colab.research.google.com/github/lordfemcel/Black-Scholes/blob/main/Risk_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Developing a machine learning model to predict the likelihood of loan default using historical loan and borrower data

In [6]:
import pandas as pd

In [8]:
data=pd.read_csv('/loans_2007.csv')

In [3]:
print(data.head())

   loan_amnt  int_rate  installment  emp_length  annual_inc  loan_status  \
0     5000.0     10.65       162.87          10     24000.0            1
1     2500.0     15.27        59.83           0     30000.0            0
2     2400.0     15.96        84.33          10     12252.0            1
3    10000.0     13.49       339.31          10     49200.0            1
4     5000.0      7.90       156.46           3     36000.0            1

   zip_code    dti  delinq_2yrs  fico_range_high  ...  purpose_major_purchase  \
0       860  27.65          0.0            739.0  ...                     0.0
1       309   1.00          0.0            744.0  ...                     0.0
2       606   8.72          0.0            739.0  ...                     0.0
3       917  20.00          0.0            694.0  ...                     0.0
4       852  11.20          0.0            734.0  ...                     0.0

   purpose_medical  purpose_moving  purpose_other  purpose_renewable_energy  \
0              0.0             0.0            0.0                       0.0
1              0.0             0.0            0.0                       0.0
2              0.0             0.0            0.0                       0.0
3              0.0             0.0            1.0                       0.0
4              0.0             0.0            0.0                       0.0

   purpose_small_business  purpose_vacation  purpose_wedding  term_ 36 months  \
0                     0.0               0.0              0.0              1.0
1                     0.0               0.0              0.0              0.0
2                     1.0               0.0              0.0              1.0
3                     0.0               0.0              0.0              1.0
4                     0.0               0.0              1.0              1.0

   term_ 60 months
0              0.0
1              1.0
2              0.0
3              0.0
4              0.0

[5 rows x 41 columns]

In [9]:
data.describe()

,loan_amnt,int_rate,installment,emp_length,annual_inc,loan_status,zip_code,dti,delinq_2yrs,fico_range_high,...,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding,term_ 36 months,term_ 60 months
count,39252.000000,39252.000000,39252.000000,39252.000000,3.925200e+04,39252.000000,39252.000000,39252.000000,39252.000000,39252.000000,...,39252.000000,39252.000000,39252.000000,39252.000000,39252.000000,39252.000000,39252.000000,39252.000000,39252.000000,39252.000000
mean,11137.180271,11.982838,323.311302,4.826047,6.888910e+04,0.855651,502.382834,13.295056,0.146617,718.996179,...,0.055640,0.017579,0.014827,0.100326,0.002624,0.045781,0.009630,0.023973,0.741262,0.258738
std,7400.231838,3.708876,208.472820,3.603563,6.399421e+04,0.351448,329.753183,6.676636,0.491688,35.868039,...,0.229229,0.131416,0.120863,0.300438,0.051159,0.209013,0.097661,0.152968,0.437947,0.437947
min,500.000000,5.420000,15.690000,0.000000,4.000000e+03,0.000000,7.000000,0.000000,0.000000,629.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5400.000000,8.940000,166.310000,2.000000,4.003500e+04,1.000000,200.000000,8.160000,0.000000,689.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,10000.000000,11.830000,279.090000,4.000000,5.900000e+04,1.000000,448.000000,13.390000,0.000000,714.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,15000.000000,14.460000,427.370000,9.000000,8.200000e+04,1.000000,852.000000,18.580000,0.000000,744.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,35000.000000,24.590000,1305.190000,10.000000,6.000000e+06,1.000000,999.000000,29.990000,11.000000,829.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
len(data.columns)

41

In [10]:
print(data.isnull().sum())

loan_amnt                               0
int_rate                                0
installment                             0
emp_length                              0
annual_inc                              0
loan_status                             0
zip_code                                0
dti                                     0
delinq_2yrs                             0
fico_range_high                         0
inq_last_6mths                          0
open_acc                                0
pub_rec                                 0
revol_bal                               0
revol_util                             50
total_acc                               0
last_fico_range_high                    0
home_ownership_MORTGAGE                 0
home_ownership_NONE                     0
home_ownership_OTHER                    0
home_ownership_OWN                      0
home_ownership_RENT                     0
verification_status_Not Verified        0
verification_status_Source Verified     0
verification_status_Verified            0
purpose_car                             0
purpose_credit_card                     0
purpose_debt_consolidation              0
purpose_educational                     0
purpose_home_improvement                0
purpose_house                           0
purpose_major_purchase                  0
purpose_medical                         0
purpose_moving                          0
purpose_other                           0
purpose_renewable_energy                0
purpose_small_business                  0
purpose_vacation                        0
purpose_wedding                         0
term_ 36 months                         0
term_ 60 months                         0
dtype: int64

In [12]:
len(data)

39252

In [13]:
data = data.fillna(data.mean())

In [14]:
data

,loan_amnt,int_rate,installment,emp_length,annual_inc,loan_status,zip_code,dti,delinq_2yrs,fico_range_high,...,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding,term_ 36 months,term_ 60 months
0,5000.0,10.65,162.87,10,24000.0,1,860,27.65,0.0,739.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2500.0,15.27,59.83,0,30000.0,0,309,1.00,0.0,744.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2400.0,15.96,84.33,10,12252.0,1,606,8.72,0.0,739.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,10000.0,13.49,339.31,10,49200.0,1,917,20.00,0.0,694.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,5000.0,7.90,156.46,3,36000.0,1,852,11.20,0.0,734.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39247,2500.0,8.07,78.42,4,110000.0,1,802,11.33,0.0,764.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
39248,8500.0,10.28,275.38,3,18000.0,1,274,6.40,1.0,694.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
39249,5000.0,8.07,156.84,0,100000.0,1,17,2.30,0.0,744.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
39250,5000.0,7.43,155.38,0,200000.0,1,208,3.72,0.0,814.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
39251,7500.0,13.75,255.43,0,22000.0,1,27,14.29,1.0,664.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score

In [18]:
# Feature selection
features = data.drop('loan_status', axis=1)
target = data['loan_status']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.1, random_state=42)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Model training
model = LogisticRegression()
model.fit(X_train, y_train)

# Model evaluation
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print('AUC-ROC:', roc_auc_score(y_test, model.predict_proba(X_test)[:, 1]))

              precision    recall  f1-score   support

           0       0.69      0.45      0.54       557
           1       0.91      0.97      0.94      3369

    accuracy                           0.89      3926
   macro avg       0.80      0.71      0.74      3926
weighted avg       0.88      0.89      0.88      3926

AUC-ROC: 0.9145178901729947